version: '3.8'

services:
    frontend:
        build: .
        container_name: initcrm-frontend
        restart: unless-stopped
        ports:
            - '3000:80'
        networks:
            - frontend-network

networks:
    frontend-network:
        driver: bridge
