version: '3.8'

services:
    frontend:
        build: .
        container_name: initcrm-frontend
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./dist:/usr/share/nginx/html
        networks:
            - frontend-network

networks:
    frontend-network:
        driver: bridge
